# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "test"
  - "build"
  - "mystep"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "https://github.com/sambitpal001/create-pact-webhook"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "master"
    git: "github"
    stage: "clone"

  test:
    title: "Compile/Unit test"
    type: "freestyle" # Run any command
    image: "maven:3.6.3-adoptopenjdk-11" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package
    stage: test

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "pals2/create-pact-webhook"
    working_directory: "${{clone}}"
    tag: "latest"
    registry: "dockerhub"
    dockerfile: "Dockerfile"
    stage: "build"

  mystep:
    title: "Run Docker image"
    stage: "mystep"
    image: "pals2/create-pact-webhook:latest"
    commands:   
      - pwd
      - ls    
      - java -jar ./create-pact-webhook/target/create-pact-webhook-1.0-SNAPSHOT.jar
      - exit
#     services:
#       composition:
#         my-spring-app:
#           image: pals2/create-pact-webhook:latest
#           ports:
#            - 8080